version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[[transformers]]
name = "rustfmt"