name: Build docker images
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert GITHUB_REPOSITORY into lowercase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build for x86_64
        run: |
            docker build -t bot:latest .
      - name: Push docker image
        run: |
            docker tag bot:latest ghcr.io/${REPO}:latest
            docker push ghcr.io/${REPO}:latest